---
# Source: helm for kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nakfake-11b8ba4e          # Service name
  labels:
    app: nakfake-11b8ba4e
spec:
  type: ClusterIP   # Service type (ClusterIP, NodePort, LoadBalancer)
  selector:
    app: nakfake-11b8ba4e         # Matches Deployment labels
  ports:
    - protocol: TCP
      port: 8080         # Service port
      targetPort: 8080  # Target container port
